### ISSUE TITLE
Auto Catcher Bot help.

### ISSUE THREAD

**Issue by ItzXRory** [Hyperclaw79/PokeBall-SelfBot-Poketwo-Automation#209]
When i made a new application and a bot and then i run setup.bat theb i write the token, it is fine. but until i do run.bat it came up with an error and the bot is not online.

**Comment by Hyperclaw79** [comment]
1. Your description barely conveys any information about the issue. Follow the template provided, it's there for a reason.
2.  Autocatcher is a Premium Version only feature, it won't work on this one even if the selfbot itself works.
