### ISSUE TITLE
Bot not accepting owner ID?

### ISSUE THREAD

**Issue by vekst** [Hyperclaw79/PokeBall-SelfBot-Poketwo-Automation#210]
Hi there. I've been having issues with the bot, with it saying that I entered a wrong ID for the owner account / don't share a server with it. The problem is, the ID is indeed correct and that the bot account and the alt do share a server. I'm really stumped on this as I've tried everything (making a new server, trying with a different alts ID) but nothing seems to work. "Owner" will show None: (the ID), but it will display the correct tag if I use the bots own ID.

![image](https://user-images.githubusercontent.com/20705525/107705759-3a588380-6c8d-11eb-8081-7d552ec2cf5f.png)

![image](https://user-images.githubusercontent.com/20705525/107705770-40e6fb00-6c8d-11eb-87f6-573ea8214a24.png)

GIF of me getting the alts ID: https://i.diverse.graphics/m5A6W.gif

![image](https://user-images.githubusercontent.com/20705525/107705850-66740480-6c8d-11eb-82ac-4a350c8835f3.png)

**Comment by Hyperclaw79** [comment]
This is because of Discord's api changes. Your best bet would be to make
both the accounts friends. Maybe DM once before starting the bot.

**Comment by Hyperclaw79** [comment]
Moved to DMs.
