### ISSUE TITLE
Getting some errors

### ISSUE THREAD

**Issue by Illusion07** [Hyperclaw79/PokeBall-SelfBot-Poketwo-Automation#216]
I have been some error! Can anyone pls help me with it?
![unknown](https://user-images.githubusercontent.com/79406161/108625765-ae0b4500-7472-11eb-8ff1-9209e8ca3087.png)

I am not familiar with python!

**Comment by Hyperclaw79** [comment]
Can barely make any sense from that screenshot. Follow the issue template provided, it exists for a reason.
Also, you don't need to know python for this, just run it using the run.bat.

Feel free to reopen this issue and follow the template.
