### ISSUE TITLE
pokenames.json

### ISSUE THREAD

**Issue by adreuotfriotggxdpro** [Hyperclaw79/PokeBall-SelfBot-Poketwo-Automation#222]
How can I get the pokemon name code version of a pokemon

What the title says, basically. I just want to know how I can get the code from pokenames.json when i get a pokemon. For example, a hoothoot appears and i just want to get its code version, which i found in the file pokenames.json.

Btw i’m using the poke realm bot.

Thanks

**Comment by Hyperclaw79** [comment]
Most of the hashes won't work anymore on Pokrealm, and definitely not on
Poketwo. The only way to detect the pokemons is using AI. The only AI that
actually works is trained by me personally and is used in the Autocatcher,
which is available in the Premium Version.
